title: History wiki
description: History tidbits
baseurl: "/docs" 
url: ""
github_username:  sergiorgiraldo

markdown: kramdown

show_downloads: false

theme: minima
plugins:
  - jekyll-remote-theme 
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/