title: History wiki
# email: sergiorgiraldo@gmail.com
description: History tidbits
baseurl: "/docs" 
url: ""
# twitter_username: sergiorgiraldo
github_username:  sergiorgiraldo

markdown: kramdown

show_downloads: false

theme: minima
# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
#   - jekyll-remote-theme 
#   - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/